# Generated by Django 5.1.2 on 2024-10-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docVisits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
